name: "Continous Deployment Workflow"
"on":
  push:
    tags:
      - v*
  
jobs:
  delivery:
    uses: ./.github/workflows/continous-delivery.yml
  update-manifest-repo:
    needs: delivery
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          repository: vegaprotocol/k8s
          path: k8s
      - run: |
          
          version=$(git describe --tags --abbrev=0)
          
          git config --global user.name 'vega-ci-bot'
          git config --global user.email 'dev@vega.xyz'
                    
          echo -n "$version" > k8s/charts/apps/tranches/fairground/VERSION
          
                    (
            cd k8s
            git add -A
            git commit -m "Automated version update for tranches: $version, from repository: $GITHUB_REPOSITORY"
            git pull --rebase
            git push
          )